name: Rust

on:
  workflow_dispatch: ~
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux_binary:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cargo build --verbose --release --locked --target x86_64-unknown-linux-musl
