name: Rust

on:
  workflow_dispatch: ~
  push: ~
  pull_request:
    branches: [ master ]

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --locked --verbose
      - name: List build
        run: ls -a ./target/release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            README.md
            ./target/release/serve-env
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
