name: Rust

on:
  workflow_dispatch: ~
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --locked --verbose
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# env:
#   CARGO_TERM_COLOR: always

# jobs:
#   build_linux_binary:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - run: cargo build --verbose --release --locked --target x86_64-unknown-linux-musl
